### PR TITLE
Resolve type aliases in docblocks

### PR DESCRIPTION
**Pull request by CHItA**
Issue: #23

### CODE REVIEW

**Comment by CHItA** [comment]
@williamdes the aliases from the context don't seem to be used elsewhere, so the later changes should work fine, and not break anyone's builds. I also added unit tests to prevent regression. I consider this PR finished and ready to be merged. If you find anything let me know.

**Review by williamdes — APPROVED** [review]
This looks good, I will have another time a look onto your work

**Comment by williamdes** [comment]
Closing to try to trigger the CIs

**Comment by CHItA** [comment]
As far as I know
```
pull_request:
        branches:
            - main
```
should be enough, there is no need to match the name of my branch.

**Comment by williamdes** [comment]
> As far as I know
> 
> ```
> pull_request:
>         branches:
>             - main
> ```
> 
> should be enough, there is no need to match the name of my branch.

is that to specify the PR target ?

**Comment by CHItA** [comment]
Yup.

**Comment by williamdes** [comment]
> Yup.

Awesome, thank you so much !

All tests pass except php 7.1
https://github.com/code-lts/doctum/pull/24/checks?check_run_id=1664642199#step:7:14

Would you too agree to drop support for PHP 7.1 ?

**Comment by CHItA** [comment]
It is fine by me. Not sure why this would fail though.

**Comment by williamdes** [comment]
> It is fine by me. Not sure why this would fail though.

It fails because they have a version that is PHP <= 7.1 compatible and one that is compatible PHP > 7.1
Many hacks for some support..
Anyway, I will do more work on this before merging your work
Thank you for your help, this seems to be perfect

**Review by williamdes — APPROVED** [review]
:100:

**Comment by williamdes** [comment]
I released [5.4.0-dev phar](https://doctum.long-term.support/releases/5.4.0-dev/doctum.phar), you can try it out and let me know ;)

**Comment by CHItA** [comment]
Seems to work great, thanks.

**Pull request merged**
