### PR TITLE
attempt fixing #18

### LINKED ISSUE #18: PHAR fails when relative cache || build path is used
With 5.2.1, the phar version fails to create directories within cache or build path, when relative cache/build paths are used in config. Here is an example run:

```console
ptomulik@barakus:$ php bin/doctum.phar update --force -vvv docs/doctum-relative.conf.php 
 Updating project 

Version main
-------------


In Filesystem.php line 105:
                                                            
  [Symfony\Component\Filesystem\Exception\IOException]      
  Failed to create "docs/cache/html": mkdir(): File exists  
                                                            

Exception trace:
  at phar:///tmp/test/bin/doctum.phar/vendor/symfony/filesystem/Filesystem.php:105
 Symfony\Component\Filesystem\Filesystem->mkdir() at phar:///tmp/test/bin/doctum.phar/src/Project.php:380
 Doctum\Project->flushDir() at phar:///tmp/test/bin/doctum.phar/src/Project.php:431
 Doctum\Project->prepareDir() at phar:///tmp/test/bin/doctum.phar/src/Project.php:374
 Doctum\Project->getCacheDir() at phar:///tmp/test/bin/doctum.phar/src/Store/JsonStore.php:76
 Doctum\Store\JsonStore->getStoreDir() at phar:///tmp/test/bin/doctum.phar/src/Store/JsonStore.php:64
 Doctum\Store\JsonStore->flushProject() at phar:///tmp/test/bin/doctum.phar/src/Project.php:464
 Doctum\Project->parseVersion() at phar:///tmp/test/bin/doctum.phar/src/Project.php:125
 Doctum\Project->update() at phar:///tmp/test/bin/doctum.phar/src/Console/Command/Command.php:183
 Doctum\Console\Command\Command->update() at phar:///tmp/test/bin/doctum.phar/src/Console/Command/UpdateCommand.php:54
 Doctum\Console\Command\UpdateCommand->execute() at phar:///tmp/test/bin/doctum.phar/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at phar:///tmp/test/bin/doctum.phar/vendor/symfony/console/Application.php:1009
 Symfony\Component\Console\Application->doRunCommand() at phar:///tmp/test/bin/doctum.phar/vendor/symfony/console/Application.php:273
 Symfony\Component\Console\Application->doRun() at phar:///tmp/test/bin/doctum.phar/vendor/symfony/console/Application.php:149
 Symfony\Component\Console\Application->run() at phar:///tmp/test/bin/doctum.phar/bin/doctum-binary.php:26
 include() at /tmp/test/bin/doctum.phar:9

update [--only-version ONLY-VERSION] [--force] [--output-format OUTPUT-FORMAT] [--no-progress] [--ignore-parse-errors] [--] <config>
```

The problem does not appear with non-phar version. Absolute paths work well.

I attach an archive containing a minimal example. The issue looks very strange and may be related to Symfony\Filesystem.

[test.tar.gz](https://github.com/code-lts/doctum/files/5664032/test.tar.gz)

### PR DESCRIPTION
**Pull request by ptomulik**
This makes my [test.tar.gz](https://github.com/code-lts/doctum/files/5726349/test.tar.gz) to work, so I believe it fixes #18. To test it, please  ``tar -xzf test.tar.gz && cd test/ && doctum.phar update --force -v docs/doctum-relative.conf.php`` (using doctum.phar generated from this PR).

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
:100: 
I will add your tests to have integration tests on this project

**Comment by williamdes** [comment]
By the way do you have a GPG key ?

**Comment by ptomulik** [comment]
> 
> 
> By the way do you have a GPG key ?

Not ATM. I mean I used a GPG key(s) for email but it got me a lot of headache at the day when my signeture expired, so I just abandoned my GPGs  for  amoment :)

**Comment by williamdes** [comment]
> Not ATM. I mean I used GPG key(s) for email but it got me a lot of headache one day my signature expired, so I just abandoned my GPGs for a moment :)

If you still have the private key you can extend the expiration date and use them ;)
This can be useful to upload the key: https://gist.github.com/williamdes/0d49288fecf83bf491cc1e6366ae7c30#upload-the-key
I can help you if you want, let 2021 be a year with a working key to sign commits and tags ;p

**Comment by williamdes** [comment]
I added bash tests: https://github.com/code-lts/doctum/runs/1595354287?check_suite_focus=true#step:4:132

**Comment by williamdes** [comment]
5.3.1 is out with your fix, thank you !

**Pull request merged**
