### PR TITLE
Fix - Not url encoding the version string used for navigation

### PR DESCRIPTION
**Pull request by mad-briller**
Me again!

I've resolved the issues outlined in the prior PR #31;

- signed the commits using the correct email
- no longer made the unnecessary changes to the tests
- used the `url_encode` twig filter rather than creating a property on the Version class

Thanks for your input on the changes, and again for the great utility.

Hope my Github naivety wasn't too frustrating :angel:

### CODE REVIEW

**Comment by mad-briller** [comment]
now Github is complaining my email is undeliverable :sob: i cannot win

**Comment by williamdes** [comment]
> now Github is complaining my email is undeliverable 😭 i cannot win

Do you mean In the emails emails list?
If yes I can heave a look as I have some expertise with emails and configs

**Review by williamdes — APPROVED** [review]
💯

**Comment by williamdes** [comment]
> Hope my Github naivety wasn't too frustrating 👼

Now worries nothing wrong :)

You signed my GPG, I LOVE it!

**Comment by mad-briller** [comment]
> > now Github is complaining my email is undeliverable sob i cannot win
> 
> Do you mean In the emails emails list?
> If yes I can heave a look as I have some expertise with emails and configs

I've fixed it so it doesn't show up in the pr anymore, but the email address i originally used was bouncing github emails for some reason, so i changed to a different one and resigned the commit

The GPG signing is a nice touch that i hadn't seen before, will have to investigate with other providers i use.

Thanks for your time on this issue mate

**Comment by williamdes** [comment]
Thank you too!
Will merge this soon

**Comment by mad-briller** [comment]
I can use the 5.4.2-dev phar in our ci setup for now, i'll keep an eye out for when a release is made, thanks!

**Comment by williamdes** [comment]
> I can use the 5.4.2-dev phar in our ci setup for now, i'll keep an eye out for when a release is made, thanks!

By the way if you use GitHub actions I published an action for Doctum

Will try to keep in mind to post a message here

Thank you for contributing!

You can use the subscribe custom to releases only on GitHub

**Comment by mad-briller** [comment]
unfortunately we use bitbucket + pipelines so i've written something custom, but thanks for the heads up

and good idea on subscribing to releases!

**Comment by williamdes** [comment]
Hi @mad-briller 

I am pushing more changes into 5.x before making a release, could you please try the latest dev phar ?

See: https://github.com/code-lts/doctum#installation
```
curl -O https://doctum.long-term.support/releases/5-dev/doctum.phar && chmod +x doctum.phar
```

**Comment by mad-briller** [comment]
hey @williamdes sorry for the delay, only just seen this,

just tested the new release and it works great, thank you!

**Comment by williamdes** [comment]
Hi @mad-briller  
The version [5.5.0](https://github.com/code-lts/doctum/releases/tag/v5.5.0) is out 🎉 
This fix is included in the version released

**Pull request merged**
