### PR TITLE
Support `@category` tags

### LINKED ISSUE #53: Supporting the `@group` / `@category` tags
We use the `@group` tag to indicate which groups a method belongs to, since `@category` was deprecated.

Is this something you'd be open to support inside Doctum optionally, or should we use our own theme to display that tag?

Either unofficial `@group`, or the old `@category`.

### PR DESCRIPTION
**Pull request by tillkruss**
Closes #53.

### CODE REVIEW

**Comment by tillkruss** [comment]
@williamdes This is how we do it currently, any feedback?

**Comment by williamdes** [comment]
> @williamdes This is how we do it currently, any feedback?

Looks good, I will test this and merge if everything is okay

**Comment by tillkruss** [comment]
I didn't add the `@group` parameter alias, feel free to add it, or leave it out since it's not official spec.

**Comment by williamdes** [comment]
I also added the support for `@category` on classes in 5961e2c747e45ac1fa0bd2ef594960d243013fa5

**Comment by williamdes** [comment]
> I didn't add the `@group` parameter alias, feel free to add it, or leave it out since it's not official spec.

Let's agree to not support non standard things for now ^^

**Comment by williamdes** [comment]
I updated the dev phar, it should be working with your work inside it.
Let me know

**Pull request merged**
